services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: ${SQL_CONNECTION_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./init:/docker-entrypoint-initdb.d 
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/entrypoint.sh"]

  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:${KAFKA_PORT},CONTROLLER://kafka:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://${KAFKA_HOST}:${KAFKA_PORT}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list" ]
      interval: 10s
      timeout: 10s
      retries: 10
      
  kafkajob:
    build:
      context: .
      dockerfile: KafkaJob/Dockerfile
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - SQL_HOST=sqlserver
      - SQL_CONNECTION=${SQL_CONNECTION}
    networks:
      - default
    depends_on:
      sqlserver:
        condition: service_started
      kafka:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    container_name: AlzaProductApi
    ports:
      - "${API_PORT_HTTP}:${API_PORT_HTTP}"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:${API_PORT_HTTP}
      - SQL_HOST=sqlserver
      - SQL_CONNECTION=${SQL_CONNECTION}
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    depends_on:
      sqlserver:
        condition: service_started
      kafka:
        condition: service_healthy

volumes:
  sql_data: